    !SNESFM_CFG_EXTERNAL = 1

    !SNESFM_CFG_SAMPLE_GENERATE = 1

    !SNESFM_CFG_SAMPLE_USE_FILTER1 = 1

    !SNESFM_CFG_PHASEMOD = 1
    !SNESFM_CFG_PULSEGEN = 1

    !SNESFM_CFG_LONG_SMP_GEN = 1
    !SNESFM_CFG_SHORTSMP_GEN = 1

    !SNESFM_CFG_INSGEN_REPEAT_AMOUNT = 2
    !SNESFM_CFG_INSGEN_ARITHMETIC_AMOUNT = 0

    !SNESFM_CFG_PITCHTABLE_GEN = 1

    incsrc "SNESFM.asm"

    startpos SPC_Init