    !SNESFM_CFG_EXTERNAL = 1

    !SNESFM_CFG_SAMPLE_GENERATE = 1

    !SNESFM_CFG_SAMPLE_USE_FILTER1 = 1

    !SNESFM_CFG_PHASEMOD_BOTH = 1
    !SNESFM_CFG_PULSEGEN_BOTH = 1

    !SNESFM_CFG_RESAMPLE = 1

    !SNESFM_CFG_INSGEN_REPEAT_AMOUNT = 2
    !SNESFM_CFG_INSGEN_ARITHMETIC_AMOUNT = 0

    !SNESFM_CFG_PITCHTABLE_GEN = 1
    !SNESFM_CFG_PITCHTABLE_GEN_ARITHMETIC_METHOD = 0
    !SNESFM_CFG_PITCHTABLE_GEN_DYNAMIC_RATIOS = 0
    !SNESFM_CFG_PITCHTABLE_GEN_DYNAMIC_NOTE_COUNTS = 0

    !SNESFM_CFG_HARDWARE_NOISE_SUPPORT	= 1

    !SNESFM_CFG_FINE_PITCH = 1
    !SNESFM_CFG_INSTRUMENT_PITCHBEND = 1
    !SNESFM_CFG_PITCH_SLIDE = 1

    !SNESFM_CFG_VIRTUAL_CHANNELS = 1

    incsrc "SNESFM.asm"