;Song data variables for more readability when assembling manually
;Instrument data
;   Flags
!UPD_SAMPLE = %01000000
!SAMPLE_SUBPAGE_0 = %00000000
!SAMPLE_SUBPAGE_1 = %00010000
!SAMPLE_SUBPAGE_2 = %00100000
!SAMPLE_SUBPAGE_3 = %00110000
!UPD_SMP_POS_RELATIVE = %00001000   ;Unimplemented
!UPD_ENVELOPE = %00000100
!UPD_ARPEGGIO = %00000010
!UPD_PITCHBEND = %00000001          ;Unimplemented
;   GAIN Envelopes
!ENV_DIRECT = %00000000
!ENV_DECREASE_LINEAR = %10000000
!ENV_DECREASE_EXPONENTIAL = %10100000
!ENV_INCREASE_LINEAR = %11000000
!ENV_INCREASE_LINEAR = %11100000
;   Commands
!COMMAND_CHANGE_INSTRUMENT_TYPE = %10000000
;   Instrument types
!SAMPLE_HIGH_PAGE_0 = %00000000
!SAMPLE_HIGH_PAGE_1 = %00010000
!SAMPLE_USE_INDEX = %00001000
!PITCHBEND_ABSOLUTE = %00000000
!PITCHBEND_RELATIVE = %00000100
!ENVELOPE_TYPE_ADSR = %00000000
!ENVELOPE_TYPE_GAIN = %00000010
!INSTRUMENT_TYPE_NOISE = %0000000
!INSTRUMENT_TYPE_SAMPLE = %00000001 
;Song data
!WAIT = $FD
!KEY_OFF = $FE
;Common shit
!END_DATA = $FF

!CH1_SONG_POINTER_L = $00
!CH1_SONG_POINTER_H = $01
!CH1_EFFECT_POINTER_L = $02
!CH1_EFFECT_POINTER_H = $03
!CH1_INSTRUMENT_POINTER_L = $04
!CH1_INSTRUMENT_POINTER_H = $05
!CH1_SAMPLE_POINTER_L = $06
!CH1_SAMPLE_POINTER_H = $07

!CH1_SONG_COUNTER = $40
!CH1_EFFECT_COUNTER = $41
!CH1_INSTRUMENT_COUNTER = $42
!CH1_INSTRUMENT_TYPE = $43
!CH1_ARPEGGIO = $45
!CH1_NOTE = $46
!CH1_FLAGS = $47


;Temporary variables, basically a shitton of names for the same thing
;$D0-DF are usually inputs while $E0-EF are just temporary variables used by routines
!ECH_FIR_FIRSTBYTE = $D0

!PUL_OUT_PAGE = $D0
!PUL_DUTY = $D1
!PUL_FLAGS = $D2

!MOD_CAR_PAGE = $D0
!MOD_MOD_PAGE = $D1
!MOD_OUT_PAGE = $D2
!MOD_MOD_STRENGTH = $D3
!MOD_MOD_PHASE_SHIFT = $D4
!MOD_SUBPAGE = $D5

!CHG_BIT_ADDRESS = $D0

!LTS_IN_PAGE = $D0
!LTS_OUT_PAGE = $D1
!LTS_OUT_SUBPAGE = $D2

!BRR_PCM_PAGE = $D0
!BRR_OUT_INDEX = $D1
!BRR_FLAGS = $D2

!PUL_OUT_PTR_L = $EE
!PUL_OUT_PTR_H = $EF

!LTS_IN_PTR_L = $EC
!LTS_IN_PTR_H = $ED
!LTS_OUT_PTR_L = $EE
!LTS_OUT_PTR_H = $EF

!MOD_CAR_INDEX_L = $E8
!MOD_END_INDEX_L = $E9
!MOD_OUT_INDEX_L = $EA
!MOD_OUT_INDEX_H = $EB
!MOD_MOD_INDEX_L = $EC
!MOD_MOD_INDEX_H = $ED
!MOD_MAIN_TEMP_L = $EE
!MOD_MAIN_TEMP_H = $EF

!BRR_BUFF1_PTR_L = $20
!BRR_BUFF1_PTR_H = $21
!BRR_MAXM0_L = $F8  ;These registers are so unused
!BRR_MAXM0_H = $F9  ;they're practically RAM!
!BRR_TEMP_FLAGS = $E5
!BRR_SMPPT_L = $E6
!BRR_SMPPT_H = $E7
!BRR_CSMPT_L = $E8
!BRR_CSMPT_H = $E9
!BRR_LSMPT_L = $EA  ;Last sample point of previous block for filter 1 adjustment
!BRR_LSMPT_H = $EB  ;
!BRR_IN0_PTR_L = $EC
!BRR_IN0_PTR_H = $ED
!BRR_OUT_PTR_L = $EE
!BRR_OUT_PTR_H = $EF

;For channel updates, first 2 blocks of 8 bytes are stored in $C0-$CF, while the last one is stored in $D8-$DF
!CHTEMP_POINTER_0 = $BF
!CHTEMP_POINTER_1 = $C7
!CHTEMP_POINTER_2 = $D7
!CHTEMP_SONG_POINTER_L = $C0
!CHTEMP_SONG_POINTER_H = $C1
!CHTEMP_EFFECT_POINTER_L = $C2
!CHTEMP_EFFECT_POINTER_H = $C3
!CHTEMP_INSTRUMENT_POINTER_L = $C4
!CHTEMP_INSTRUMENT_POINTER_H = $C5
!CHTEMP_SAMPLE_POINTER_L = $C6
!CHTEMP_SAMPLE_POINTER_H = $C7


!CHTEMP_SONG_COUNTER = $C8
!CHTEMP_EFFECT_COUNTER = $C9
!CHTEMP_INSTRUMENT_COUNTER = $CA
!CHTEMP_INSTRUMENT_TYPE = $CB
!CHTEMP_ARPEGGIO = $CD
!CHTEMP_NOTE = $CE
!CHTEMP_FLAGS = $CF

!PATTERN_END_FLAGS = $E3
!PATTERN_POINTER_L = $E4
!PATTERN_POINTER_H = $E5

!CHTEMP_REGISTER_INDEX = $E1
