
!MOD_CAR_PAGE = $D0
!MOD_MOD_PAGE = $D1
!MOD_OUT_PAGE = $D2
!MOD_MOD_STRENGTH = $D3

!MOD_OUT_INDEX_L = $EA
!MOD_OUT_INDEX_H = $EB
!MOD_MOD_INDEX_L = $EC
!MOD_MOD_INDEX_H = $ED
!MOD_MAIN_TEMP_L = $EE
!MOD_MAIN_TEMP_H = $EF
