on: [push]

jobs:
  build_rom:
    runs-on: ubuntu-latest
    name: Compile rom
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get curl because you need to get it separately fsr
        run: sudo apt-get update && sudo apt-get install curl -y
      - name: Get Dependencies (asar)
        run: make get_dependencies
      - name: Build the thing
        run: make build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SNESFM.zip
          path: | 
            bin/SNESFMTrackDAW.sfc
            bin/SNESFM.bin
      - name: Upload artifact with debug symbols
        uses: actions/upload-artifact@v3
        with:
          name: SNESFM_With_debug_symbols.zip
          path: bin/*
