on: [push]

jobs:
  build_rom:
    runs-on: ubuntu-latest
    name: Compile rom
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Move things into the spots github CI expects them in
        run: "cp -a /root/. /github/home"
      - name: Get curl because you need to get it separately fsr
        run: apt-get update && apt-get install curl -y
      - name: Get Dependencies (asar)
        run: make get_dependencies
      - name: Build the thing
        run: make build
      - name: Start xvfb 
        run: sudo Xvfb :99 -screen 0 1280x1024x24 &
      - name: Clean up xvfb
        uses: bcomnes/cleanup-xvfb@v1
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ROM
          path: SNESFMTrackDAW.asm
